version: '3'

services:
  backend:
    build: backend/
    restart: always
  nginx:
    build: nginx/
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    environment:
      - DOMAIN=${DOMAIN}
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates:rw,cached
      - ./backend/static/:/app/static/
      - ./backend/media/:/app/media/
    restart: always
    depends_on:
      - backend